services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dbaas_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dbaas_network

  mongo:
    image: mongo:latest
    container_name: mongodb_core
    ports:
      - "27017:27017"
    networks:
      - dbaas_network

  mv3-auth:
    build: ./MV3
    container_name: mv3-auth-container
    ports:
      - "50051:50051"
    depends_on:
      - mongo
    networks:
      - dbaas_network

  mv1-database:
    build: ./MV1
    container_name: mv1-database-container
    ports:
      - "50052:50052"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - dbaas_network

  gateway:
    build: ./dbaas_proyecto
    container_name: dbaas_gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mv3-auth
      - mv1-database
    networks:
      - dbaas_network
    environment:
      - AUTH_GRPC_HOST=mv3-auth-container:50051
      - DB_GRPC_HOST=mv1-database-container:50052

networks:
  dbaas_network:
    driver: bridge
