# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dbaas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dbaas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x62\x61\x61s.proto\x12\x05\x64\x62\x61\x61s\"R\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"D\n\x0c\x41uthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"3\n\x0f\x43reateDbRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x62_name\x18\x02 \x01(\t\",\n\nDbResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"S\n\x0cQueryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x62_name\x18\x02 \x01(\t\x12\x12\n\ntable_name\x18\x03 \x01(\t\x12\r\n\x05\x66ield\x18\x04 \x01(\t\".\n\rQueryResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2y\n\x0b\x41uthService\x12\x37\n\x08Register\x12\x16.dbaas.RegisterRequest\x1a\x13.dbaas.AuthResponse\x12\x31\n\x05Login\x12\x13.dbaas.LoginRequest\x1a\x13.dbaas.AuthResponse2N\n\x0f\x44\x61tabaseService\x12;\n\x0e\x43reateDatabase\x12\x16.dbaas.CreateDbRequest\x1a\x11.dbaas.DbResponse2I\n\x0cQueryService\x12\x39\n\x0c\x41ggregateSum\x12\x13.dbaas.QueryRequest\x1a\x14.dbaas.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbaas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=22
  _globals['_REGISTERREQUEST']._serialized_end=104
  _globals['_LOGINREQUEST']._serialized_start=106
  _globals['_LOGINREQUEST']._serialized_end=153
  _globals['_AUTHRESPONSE']._serialized_start=155
  _globals['_AUTHRESPONSE']._serialized_end=223
  _globals['_CREATEDBREQUEST']._serialized_start=225
  _globals['_CREATEDBREQUEST']._serialized_end=276
  _globals['_DBRESPONSE']._serialized_start=278
  _globals['_DBRESPONSE']._serialized_end=322
  _globals['_QUERYREQUEST']._serialized_start=324
  _globals['_QUERYREQUEST']._serialized_end=407
  _globals['_QUERYRESPONSE']._serialized_start=409
  _globals['_QUERYRESPONSE']._serialized_end=455
  _globals['_AUTHSERVICE']._serialized_start=457
  _globals['_AUTHSERVICE']._serialized_end=578
  _globals['_DATABASESERVICE']._serialized_start=580
  _globals['_DATABASESERVICE']._serialized_end=658
  _globals['_QUERYSERVICE']._serialized_start=660
  _globals['_QUERYSERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
